# Generated by Django 5.1.2 on 2024-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('field', models.CharField(max_length=50, verbose_name='زمینه کاری')),
                ('intro', models.TextField(verbose_name='معرفی نامه')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='لینک توییتر')),
                ('linkdien_link', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='لینک گیتهاب')),
                ('intro_image', models.ImageField(upload_to='intro_image', verbose_name='عکس بک گراند')),
            ],
        ),
    ]
