# Generated by Django 5.1.2 on 2024-11-12 07:05

import homepage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_porfile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='نام')),
                ('lname', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, validators=[homepage.validators.iranian_phone_number_validator], verbose_name='شماره تلفن')),
                ('message', models.TextField(verbose_name='پیام ارسالی')),
            ],
        ),
    ]
