# Generated by Django 5.1.2 on 2024-11-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='service_type',
            field=models.CharField(choices=[('branding', 'طراحی برندینگ'), ('web', 'طراحی سایت'), ('uxui', 'طراحی UX/UI'), ('app', 'طراحی اپلیکیشن')], default='web', max_length=10, verbose_name='نوع خدمات'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
    ]
