# Generated by Django 5.1.2 on 2024-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_profile_email_alter_message_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='تصویر پروژه')),
                ('category', models.CharField(choices=[('uxui', 'UX/UI'), ('branding', 'Branding'), ('mobile-app', 'Mobile App')], max_length=50, verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
