# Generated by Django 5.1.2 on 2024-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True, null=True, verbose_name='عملکرد ما'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('uxui', 'UX/UI'), ('branding', 'Branding'), ('mobile-app', 'Mobile App')], max_length=50, null=True, verbose_name='دسته\u200cبندی'),
        ),
    ]
