# Generated by Django 5.1.2 on 2024-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_project_approach_project_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='approach',
        ),
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='ناشناس', max_length=100, verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.CharField(default='نام پیش\u200cفرض طراح', max_length=100, verbose_name='طراح'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='1400-01-01', verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('uxui', 'UX/UI'), ('branding', 'برندینگ'), ('mobile-app', 'اپلیکیشن موبایل')], default='uiux', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
